name: Liquibase CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt' # You can specify other distributions like 'zulu', 'temurin', etc.
        java-package: jdk
        architecture: x64

    # Add other steps here
